/*+ ETLM {  
	depend:{  
		add:[  
			 {name:"ADW_METRICS_GLUE.DIM_ADS"} 
			,{name:"ADW_METRICS_GLUE.DIM_CAMPAIGNS"}
			,{name:"ADW_METRICS_GLUE.DIM_AD_PRODUCT_TYPES"}
			,{name:"ADW_METRICS_GLUE.DIM_ADVERTISERS"}
			,{name:"ADW_METRICS_GLUE.DIM_PROPOSALS"}
			,{name:"ADW_METRICS_GLUE.DIM_BUDGETS"}
			,{name:"ADW_METRICS_GLUE.FACT_DAILY_AD_TRAFFIC"}  			
		]  
	}   
}*/


SELECT
dsat.DIM_DATE
,dp.SALESFORCE_ID 
,dadv.ADVERTISER_COUNTRY
,dc.DIM_ADVERTISER_ID
,dadv.ADVERTISER_NAME
,dc.CFID AS CAMPAIGN_CFID
,dc.CAMPAIGN_NAME
,dc.START_DT_UTC AS CAMP_START
,dc.END_DT_UTC AS CAMP_END
,da.CFID AS AD_CFID
,da.DIM_AD_ID
,da.AD_NAME
,da.START_DT_UTC AS AD_START
,da.END_DT_UTC AS AD_END
,dbud.BUDGET_AMOUNT/100000::NUMERIC(38,2)
,CASE 
WHEN da.TARGETING_COMBINED LIKE '%imdb%' THEN 'IMDB'
WHEN da.TARGETING_COMBINED LIKE '%sponsored_content_wizard_featured%' THEN 'OOBE'
WHEN da.TARGETING_COMBINED LIKE '%sponsored_tiles_horizontal%' THEN 'Sponsored Tiles'
WHEN da.TARGETING_COMBINED LIKE '%home_fr%' THEN 'Feature_Rotator'
WHEN (da.AD_TYPE = 'CLASS_I_MOBILE_APP' OR da.AD_TYPE = 'CLASS_I_MOBILE_APP_SOV') AND dapt.AD_PRODUCT_TYPE_CODE IN ('DEVICES_CLASS_I_TAKEOVER','DEVICES_CLASS_I', 'AAA_CLASS_II','AAA_CLASS_II','FIRE_TV_BANNER') THEN 'Fire TV'
WHEN (da.AD_TYPE = 'DTCP' OR da.AD_TYPE = 'AAP_MOBILE') AND dapt.AD_PRODUCT_TYPE_CODE IN ('DEVICES_CLASS_I_TAKEOVER','DEVICES_CLASS_I', 'AAA_CLASS_II') THEN 'Fire Tablet'
WHEN dapt.AD_PRODUCT_TYPE_CODE IN ('CLASS_I_MOBILE_WEB','CLASS_I_MOBILE_APP','CLASS_I_DESKTOP','CLASS_I_DESKTOP_SOV','CLASS_I_MOBILE_WEB_SOV') THEN 'Class 1'
WHEN dapt.AD_PRODUCT_TYPE_CODE IN ('AAP_DESKTOP','AAP_MOBILE_WEB','AAP_MOBILE_APP','AAA_MOBILE_NETWORK','AAA_MOBILE_OO','DEVICES_CLASS_II','AAA_FIRE_TV','AAA_KSO') THEN 'DSP'
WHEN dapt.AD_PRODUCT_TYPE_CODE IN ('AAP_VIDEO','CLASS_I_VIDEO_SOV','OTT_VIDEO_1P_GUARANTEED','CLASS_I_VIDEO','OTT_VIDEO_GUARANTEED') THEN 'Video' 
ELSE 'Other' END AS PROPERTY_TYPE
,SUM(dsat.IMP_COUNT) AS IMPRESSIONS
,SUM(dsat.CLICK_COUNT) AS CLICKS
,SUM(nvl(dsat.REVENUE_AMOUNT,0))::NUMERIC(38) AS REVENUE

FROM ADW_METRICS_GLUE.FACT_DAILY_AD_TRAFFIC dsat
INNER JOIN ADW_METRICS_GLUE.DIM_ADS da ON dsat.DIM_AD_ID = da.DIM_AD_ID
INNER JOIN ADW_METRICS_GLUE.DIM_BUDGETS dbud ON dbud.DIM_BUDGET_ID = da.DIM_BUDGET_ID
INNER JOIN ADW_METRICS_GLUE.DIM_CAMPAIGNS dc ON da.DIM_CAMPAIGN_ID = dc.DIM_CAMPAIGN_ID
INNER JOIN ADW_METRICS_GLUE.DIM_AD_PRODUCT_TYPES dapt ON da.DIM_AD_PRODUCT_TYPE_ID = dapt.DIM_AD_PRODUCT_TYPE_ID
INNER JOIN ADW_METRICS_GLUE.DIM_ADVERTISERS dadv ON dc.DIM_ADVERTISER_ID = dadv.DIM_ADVERTISER_ID
LEFT JOIN ADW_METRICS_GLUE.DIM_PROPOSALS dp ON dc.INSERTION_ORDER_ID = dp.OPR_PROPOSAL_ID

WHERE 
da.DIM_AD_ID IN (
2421836092,
2414842645,
2414731828,
2414947621,
1696478290,
2415290814,
1696343874,
2415186991,
2455974916,
1696429869)

GROUP BY 
dsat.DIM_DATE
,dp.SALESFORCE_ID 
,dadv.ADVERTISER_COUNTRY
,dc.DIM_ADVERTISER_ID
,dadv.ADVERTISER_NAME
,dc.CFID
,dc.CAMPAIGN_NAME
,dc.START_DT_UTC
,dc.END_DT_UTC
,da.CFID
,da.DIM_AD_ID
,da.AD_NAME
,da.START_DT_UTC
,da.END_DT_UTC
,dbud.BUDGET_AMOUNT/100000::NUMERIC(38,2)
,CASE 
WHEN da.TARGETING_COMBINED LIKE '%imdb%' THEN 'IMDB'
WHEN da.TARGETING_COMBINED LIKE '%sponsored_content_wizard_featured%' THEN 'OOBE'
WHEN da.TARGETING_COMBINED LIKE '%sponsored_tiles_horizontal%' THEN 'Sponsored Tiles'
WHEN da.TARGETING_COMBINED LIKE '%home_fr%' THEN 'Feature_Rotator'
WHEN (da.AD_TYPE = 'CLASS_I_MOBILE_APP' OR da.AD_TYPE = 'CLASS_I_MOBILE_APP_SOV') AND dapt.AD_PRODUCT_TYPE_CODE IN ('DEVICES_CLASS_I_TAKEOVER','DEVICES_CLASS_I', 'AAA_CLASS_II','AAA_CLASS_II','FIRE_TV_BANNER') THEN 'Fire TV'
WHEN (da.AD_TYPE = 'DTCP' OR da.AD_TYPE = 'AAP_MOBILE') AND dapt.AD_PRODUCT_TYPE_CODE IN ('DEVICES_CLASS_I_TAKEOVER','DEVICES_CLASS_I', 'AAA_CLASS_II') THEN 'Fire Tablet'
WHEN dapt.AD_PRODUCT_TYPE_CODE IN ('CLASS_I_MOBILE_WEB','CLASS_I_MOBILE_APP','CLASS_I_DESKTOP','CLASS_I_DESKTOP_SOV','CLASS_I_MOBILE_WEB_SOV') THEN 'Class 1'
WHEN dapt.AD_PRODUCT_TYPE_CODE IN ('AAP_DESKTOP','AAP_MOBILE_WEB','AAP_MOBILE_APP','AAA_MOBILE_NETWORK','AAA_MOBILE_OO','DEVICES_CLASS_II','AAA_FIRE_TV','AAA_KSO') THEN 'DSP'
WHEN dapt.AD_PRODUCT_TYPE_CODE IN ('AAP_VIDEO','CLASS_I_VIDEO_SOV','OTT_VIDEO_1P_GUARANTEED','CLASS_I_VIDEO','OTT_VIDEO_GUARANTEED') THEN 'Video' 
ELSE 'Other' END
LIMIT 1000; 



SELECT count (distinct da.cfid)
FROM ADW_METRICS_GLUE.DIM_ADS da
INNER JOIN ADW_METRICS_GLUE.DIM_CAMPAIGNS dc ON da.DIM_CAMPAIGN_ID = dc.DIM_CAMPAIGN_ID
INNER JOIN ADW_METRICS_GLUE.DIM_ADVERTISERS dadv ON dc.DIM_ADVERTISER_ID = dadv.DIM_ADVERTISER_ID
WHERE dadv.advertiser_sub_industry = 'Software Games'
AND dc.start_dt_utc::date > to_date('20181231','YYYYMMDD') 
AND dc.end_dt_utc::date < to_date('20200101','YYYYMMDD') 
limit 100; 



SELECT distinct (adv.advertiser_industry)
FROM adw_metrics_glue.dim_advertisers adv
--where adv.advertiser_name = 'Huuuge Global Limited - US'
--WHERE adv.advertiser_sub_industry = 'Software Games'
limit 100;