/*+ ETLM {  
	depend:{  
		add:[  
			 {name:"ADW_METRICS_GLUE.DIM_ADS"} 
			,{name:"ADW_METRICS_GLUE.DIM_CAMPAIGNS"}
			,{name:"ADW_METRICS_GLUE.DIM_AD_PRODUCT_TYPES"}
			,{name:"ADW_METRICS_GLUE.DIM_ADVERTISERS"}
			,{name:"ADW_METRICS_GLUE.DIM_PROPOSALS"}
			,{name:"ADW_METRICS_GLUE.DIM_BUDGETS"}			
			,{name:"ADW_METRICS_GLUE.FACT_DAILY_AD_CONVERSIONS"} 
		]  
	}   
}*/


SELECT
dsat.DIM_DATE
,dp.SALESFORCE_ID 
,dadv.ADVERTISER_COUNTRY
,dc.DIM_ADVERTISER_ID
,dadv.ADVERTISER_NAME
,dc.CFID AS CAMPAIGN_CFID
,dc.CAMPAIGN_NAME
,dc.START_DT_UTC AS CAMP_START
,dc.END_DT_UTC AS CAMP_END
,da.CFID AS AD_CFID
,da.DIM_AD_ID
,da.AD_NAME
,da.START_DT_UTC AS AD_START
,da.END_DT_UTC AS AD_END
,dbud.BUDGET_AMOUNT/100000::NUMERIC(38,2)
,CASE 
WHEN da.TARGETING_COMBINED LIKE '%imdb%' THEN 'IMDB'
WHEN da.TARGETING_COMBINED LIKE '%sponsored_content_wizard_featured%' THEN 'OOBE'
WHEN da.TARGETING_COMBINED LIKE '%sponsored_tiles_horizontal%' THEN 'Sponsored Tiles'
WHEN da.TARGETING_COMBINED LIKE '%home_fr%' THEN 'Feature_Rotator'
WHEN (da.AD_TYPE = 'CLASS_I_MOBILE_APP' OR da.AD_TYPE = 'CLASS_I_MOBILE_APP_SOV') AND dapt.AD_PRODUCT_TYPE_CODE IN ('DEVICES_CLASS_I_TAKEOVER','DEVICES_CLASS_I', 'AAA_CLASS_II','AAA_CLASS_II','FIRE_TV_BANNER') THEN 'Fire TV'
WHEN (da.AD_TYPE = 'DTCP' OR da.AD_TYPE = 'AAP_MOBILE') AND dapt.AD_PRODUCT_TYPE_CODE IN ('DEVICES_CLASS_I_TAKEOVER','DEVICES_CLASS_I', 'AAA_CLASS_II') THEN 'Fire Tablet'
WHEN dapt.AD_PRODUCT_TYPE_CODE IN ('CLASS_I_MOBILE_WEB','CLASS_I_MOBILE_APP','CLASS_I_DESKTOP','CLASS_I_DESKTOP_SOV','CLASS_I_MOBILE_WEB_SOV') THEN 'Class 1'
WHEN dapt.AD_PRODUCT_TYPE_CODE IN ('AAP_DESKTOP','AAP_MOBILE_WEB','AAP_MOBILE_APP','AAA_MOBILE_NETWORK','AAA_MOBILE_OO','DEVICES_CLASS_II','AAA_FIRE_TV','AAA_KSO') THEN 'DSP'
WHEN dapt.AD_PRODUCT_TYPE_CODE IN ('AAP_VIDEO','CLASS_I_VIDEO_SOV','OTT_VIDEO_1P_GUARANTEED','CLASS_I_VIDEO','OTT_VIDEO_GUARANTEED') THEN 'Video' 
ELSE 'Other' END AS PROPERTY_TYPE
,SUM(CASE WHEN dsat.DIM_CONV_TYPE_ID IN (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,29,30,31,32,36,37,43,44,45,46,47,48,49,53,54,55,58,81,82,83) THEN dsat.CLICK_CONVERSION_COUNT ELSE NULL END)
+SUM(CASE WHEN dsat.DIM_CONV_TYPE_ID IN (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,29,30,31,32,36,37,43,44,45,46,47,48,49,53,54,55,58,81,82,83) THEN dsat.IMPRESSION_CONVERSION_COUNT ELSE NULL END) AS CONVERSIONS
,SUM(CASE WHEN dsat.DIM_CONV_TYPE_ID IN (56) THEN dsat.CLICK_CONVERSION_COUNT ELSE NULL END)+SUM(CASE WHEN dsat.DIM_CONV_TYPE_ID IN (56) THEN dsat.IMPRESSION_CONVERSION_COUNT ELSE NULL END) AS VIDEO_STARTED
,SUM(CASE WHEN dsat.DIM_CONV_TYPE_ID IN (57) THEN dsat.CLICK_CONVERSION_COUNT ELSE NULL END)+SUM(CASE WHEN dsat.DIM_CONV_TYPE_ID IN (57) THEN dsat.IMPRESSION_CONVERSION_COUNT ELSE NULL END) AS VIDEO_COMPLETED

FROM ADW_METRICS_GLUE.FACT_DAILY_AD_CONVERSIONS dsat 
INNER JOIN ADW_METRICS_GLUE.DIM_ADS da ON dsat.DIM_AD_ID = da.DIM_AD_ID
INNER JOIN ADW_METRICS_GLUE.DIM_BUDGETS dbud ON dbud.DIM_BUDGET_ID = da.DIM_BUDGET_ID
INNER JOIN ADW_METRICS_GLUE.DIM_CAMPAIGNS dc ON da.DIM_CAMPAIGN_ID = dc.DIM_CAMPAIGN_ID
INNER JOIN ADW_METRICS_GLUE.DIM_AD_PRODUCT_TYPES dapt ON da.DIM_AD_PRODUCT_TYPE_ID = dapt.DIM_AD_PRODUCT_TYPE_ID
INNER JOIN ADW_METRICS_GLUE.DIM_ADVERTISERS dadv ON dc.DIM_ADVERTISER_ID = dadv.DIM_ADVERTISER_ID
LEFT JOIN ADW_METRICS_GLUE.DIM_PROPOSALS dp ON dc.INSERTION_ORDER_ID = dp.OPR_PROPOSAL_ID

WHERE 
da.CFID IN (
'1360145230601',
'8138015540201',
'8259773750701',
'9179201770601',
'4476748850801',
'1970276950301',
'4227426170601',
'6881260480701',
'1207217420001',
'4054642220201')
AND dsat.DIM_CONV_TYPE_ID in (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,29,30,31,32,36,37,43,44,45,46,47,48,49,53,54,55,56,57,58,59,60,61,62,63,64,80,81,82,83)

GROUP BY 
dsat.DIM_DATE
,dp.SALESFORCE_ID 
,dadv.ADVERTISER_COUNTRY
,dc.DIM_ADVERTISER_ID
,dadv.ADVERTISER_NAME
,dc.CFID
,dc.CAMPAIGN_NAME
,dc.START_DT_UTC
,dc.END_DT_UTC
,da.CFID
,da.DIM_AD_IDå
,da.AD_NAME
,da.START_DT_UTC
,da.END_DT_UTC
,dbud.BUDGET_AMOUNT/100000::NUMERIC(38,2)
,CASE 
WHEN da.TARGETING_COMBINED LIKE '%imdb%' THEN 'IMDB'
WHEN da.TARGETING_COMBINED LIKE '%sponsored_content_wizard_featured%' THEN 'OOBE'
WHEN da.TARGETING_COMBINED LIKE '%sponsored_tiles_horizontal%' THEN 'Sponsored Tiles'
WHEN da.TARGETING_COMBINED LIKE '%home_fr%' THEN 'Feature_Rotator'
WHEN (da.AD_TYPE = 'CLASS_I_MOBILE_APP' OR da.AD_TYPE = 'CLASS_I_MOBILE_APP_SOV') AND dapt.AD_PRODUCT_TYPE_CODE IN ('DEVICES_CLASS_I_TAKEOVER','DEVICES_CLASS_I', 'AAA_CLASS_II','AAA_CLASS_II','FIRE_TV_BANNER') THEN 'Fire TV'
WHEN (da.AD_TYPE = 'DTCP' OR da.AD_TYPE = 'AAP_MOBILE') AND dapt.AD_PRODUCT_TYPE_CODE IN ('DEVICES_CLASS_I_TAKEOVER','DEVICES_CLASS_I', 'AAA_CLASS_II') THEN 'Fire Tablet'
WHEN dapt.AD_PRODUCT_TYPE_CODE IN ('CLASS_I_MOBILE_WEB','CLASS_I_MOBILE_APP','CLASS_I_DESKTOP','CLASS_I_DESKTOP_SOV','CLASS_I_MOBILE_WEB_SOV') THEN 'Class 1'
WHEN dapt.AD_PRODUCT_TYPE_CODE IN ('AAP_DESKTOP','AAP_MOBILE_WEB','AAP_MOBILE_APP','AAA_MOBILE_NETWORK','AAA_MOBILE_OO','DEVICES_CLASS_II','AAA_FIRE_TV','AAA_KSO') THEN 'DSP'
WHEN dapt.AD_PRODUCT_TYPE_CODE IN ('AAP_VIDEO','CLASS_I_VIDEO_SOV','OTT_VIDEO_1P_GUARANTEED','CLASS_I_VIDEO','OTT_VIDEO_GUARANTEED') THEN 'Video' 
ELSE 'Other' END
LIMIT 1000;
